apiVersion: v1
kind: Service
metadata:
  name: heart-disease-service
  labels:
    app: heart-disease
spec:
  type: LoadBalancer
  selector:
    app: heart-disease
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
